name: Monthly Dotfiles Check

on:
  schedule:
    - cron: '0 0 1 * *'  # 毎月1日 0:00 UTC
  workflow_dispatch:     # 手動実行も可能

jobs:
  test-dotfiles:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: zsh, starship, python, nodejs など必要なツールをインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh git python3 python3-venv nodejs npm
          curl -sS https://starship.rs/install.sh | sh -s -- -y

      - name: starshipのパスを通す
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: 仮想環境を作成・有効化
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: setup/setup.zsh を実行
        shell: zsh {0}
        run: |
          zsh setup/setup.zsh

      - name: starship.tomlのlintや内容確認（任意）
        run: |
          cat ~/.config/starship.toml

      - name: 結果を通知（失敗時のみ）
        if: failure()
        run: echo "dotfilesセットアップに失敗しました"
